# Generated by Django 3.1.3 on 2020-11-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirmation',
            field=models.CharField(choices=[(1, 'YES'), (0, 'NO')], default=0, max_length=10),
        ),
    ]
